version: "3.7"

services:
  ###########################################################################
  #######             DB SERVICES                                     #######
  ###########################################################################
  postgres:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=auth,userinfo,ride,post,rating,payment,chat,document
    networks:
      - rideshare

  auth:
    depends_on:
      - postgres
    image: hetpatel572/rideshare-be_auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./auth
        target: /app
    restart: unless-stopped
    networks:
      - rideshare

  userinfo:
    depends_on:
      - postgres
    image: hetpatel572/rideshare-be_userinfo
    build:
      context: ./userinfo
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    volumes:
      - type: bind
        source: ./userinfo
        target: /app
    restart: unless-stopped
    networks:
      - rideshare

  ride:
    depends_on:
      - postgres
    image: hetpatel572/rideshare-be_ride
    build:
      context: ./ride
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    volumes:
      - type: bind
        source: ./ride
        target: /app
    restart: unless-stopped
    networks:
      - rideshare

  post:
    depends_on:
      - postgres
    image: hetpatel572/rideshare-be_post
    build:
      context: ./post
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    volumes:
      - type: bind
        source: ./post
        target: /app
    restart: unless-stopped
    networks:
      - rideshare

  rating:
    depends_on:
      - postgres
    image: hetpatel572/rideshare-be_rating
    build:
      context: ./rating
      dockerfile: Dockerfile
    ports:
      - 8084:8080
    volumes:
      - type: bind
        source: ./rating
        target: /app
    restart: unless-stopped
    networks:
      - rideshare

  chat:
    depends_on:
      - postgres
    image: hetpatel572/rideshare-be_chat
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    volumes:
      - type: bind
        source: ./chat
        target: /app
    restart: unless-stopped
    networks:
      - rideshare

  payment:
    depends_on:
      - postgres
    image: hetpatel572/rideshare-be_payment
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - 8086:8080
    volumes:
      - type: bind
        source: ./payment
        target: /app
    restart: unless-stopped
    networks:
      - rideshare

  nginx:
    depends_on:
      - postgres
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - rideshare

networks:
  rideshare: