version: "3.7"

services:
  ###########################################################################
  #######             DB SERVICES                                     #######
  ###########################################################################
  postgres:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=auth,userinfo,ride,post,rating,payment,chat,document
    networks:
      - rideshare

  auth:
    depends_on:
      - postgres
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./auth
        target: /app
    restart: unless-stopped
    networks:
      - rideshare

  # payment:
  #   depends_on:
  #     - postgres
  #   build:
  #     context: ./payment
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8081:8080
  #   volumes:
  #     - type: bind
  #       source: ./payment
  #       target: /app
  #   restart: unless-stopped
  #   networks:
  #     - rideshare

  nginx:
    depends_on:
      - postgres
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - rideshare

networks:
  rideshare: