---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rideshare-chat
  namespace: rideshare
  labels:
    app: chat
    tier: app
spec:
  selector:
    matchLabels:
      app: chat
      tier: app
  template:
    metadata:
      labels:
        app: chat
        tier: app
    spec:
      containers:
        - image: hetpatel572/rideshare-be_chat
          name: chat
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: chat
          resources:
            requests:
              memory: "265Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: chat
  namespace: rideshare
  labels:
    app: chat
    tier: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: chat
    tier: app