---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regional-storage-class
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-ssd
  replication-type: regional-pd
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    - us-central1-a
    - us-central1-b
    - us-central1-c
    - us-central1-f

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-storage
    namespace: rideshare
spec:
  storageClassName: regional-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi