---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: rideshare
data: 
  create_multiple_db.sh: |
    #!/bin/bash

    set -e
    set -u

    function create_user_and_database() {
      local database=$1
      echo "  Creating user and database '$database'"
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          CREATE USER $database;
          CREATE DATABASE $database;
          GRANT ALL PRIVILEGES ON DATABASE $database TO $database;
    EOSQL
    }

    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
      echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
      for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        create_user_and_database $db
      done
      echo "Multiple databases created"
    fi


---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rideshare-postgres
  namespace: rideshare
  labels:
    app: postgres
    tier: db
spec:
  selector:
    matchLabels:
      app: postgres
      tier: db
  template:
    metadata:
      labels:
        app: postgres
        tier: db
    spec:
      containers:
        - image: postgres:11.7-alpine
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_MULTIPLE_DATABASES
              value: auth,userinfo,ride,post,rating,payment,chat,document
            - name: PGDATA
              value: /data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /data
            - name: postgres-migration
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "265Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-storage
        - name: postgres-migration
          configMap:
            name: postgres-init-script
            items:
            - key: create_multiple_db.sh
              path: create_multiple_db.sh

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rideshare
  labels:
    app: postgres
    tier: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer
  selector:
    app: postgres
    tier: db