---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rideshare-post
  namespace: rideshare
  labels:
    app: post
    tier: app
spec:
  selector:
    matchLabels:
      app: post
      tier: app
  template:
    metadata:
      labels:
        app: post
        tier: app
    spec:
      containers:
        - image: hetpatel572/rideshare-be_post
          name: post
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: post
          resources:
            requests:
              memory: "265Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: post
  namespace: rideshare
  labels:
    app: post
    tier: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: post
    tier: app