---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rideshare-rating
  namespace: rideshare
  labels:
    app: rating
    tier: app
spec:
  selector:
    matchLabels:
      app: rating
      tier: app
  template:
    metadata:
      labels:
        app: rating
        tier: app
    spec:
      containers:
        - image: hetpatel572/rideshare-be_rating
          name: rating
          ports:
            - containerPort: 8080
              name: rating
          resources:
            requests:
              memory: "265Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: rating
  namespace: rideshare
  labels:
    app: rating
    tier: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: rating
    tier: app