---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rideshare-userinfo
  namespace: rideshare
  labels:
    app: userinfo
    tier: app
spec:
  selector:
    matchLabels:
      app: userinfo
      tier: app
  template:
    metadata:
      labels:
        app: userinfo
        tier: app
    spec:
      containers:
        - image: hetpatel572/rideshare-be_userinfo
          name: userinfo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: userinfo
          resources:
            requests:
              memory: "265Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: userinfo
  namespace: rideshare
  labels:
    app: userinfo
    tier: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: userinfo
    tier: app