name: Docker Publish CI
on:
  push:
    tags:
      - "*"
    paths:
      - "auth/**"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata of Auth (tags, labels) for Docker
        id: auth_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: hetpatel572/rideshare-be_auth
      
      - name: Build and push Auth Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./auth
          push: true
          tags: ${{ steps.auth_meta.outputs.tags }}
          labels: ${{ steps.auth_meta.outputs.labels }}

      - name: Extract metadata of Userinfo (tags, labels) for Docker
        id: userinfo_meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: hetpatel572/rideshare-be_userinfo
      
      - name: Build and push Userinfo Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./userinfo
          push: true
          tags: ${{ steps.userinfo_meta.outputs.tags }}
          labels: ${{ steps.userinfo_meta.outputs.labels }}